### ISSUE TITLE
schematic for more led 

### ISSUE THREAD

**Issue by oremic** [NN708/ESP-Homekit-IRHub#10]
hi
Schematic for put more led iR thanks

**Comment by NN708** [comment]
I’m using a 2N3904 like this:
![sch](https://user-images.githubusercontent.com/20534082/80272491-9224fe80-86fc-11ea-9191-cc3d189e236b.png)
The resistance of resistors depends on the specifications and the quantity of your IR LEDs.

**Comment by NN708** [comment]
The issue is now closed. You can re-open it at any time if you still have the issue.
