### ISSUE TITLE
Reason using PORT 5556

### ISSUE THREAD

**Issue by anuarrozman** [NN708/ESP-Homekit-IRHub#12]
Hii, I would like to ask about PORT you are using. Is there any specific reason you are using PORT = 5556 ?

This is located inside esp-homekit/src/server.c

`#define PORT 5556`

**Comment by NN708** [comment]
For this issue you should go to [maximkulkin/esp-homekit](https://github.com/maximkulkin/esp-homekit).

**Comment by anuarrozman** [comment]
Noted. Thank you for your reply. I'll open an issue on that repo.
