### ISSUE TITLE
ir code

### ISSUE THREAD

**Issue by kiralikbeyin** [NN708/ESP-Homekit-IRHub#7]
I only saw transmit but how do you get ir codes?

**Comment by NN708** [comment]
Hi, @kiralikbeyin 
I wrote a simple program to get the IR codes, and now I have uploaded it to the repository: **[/ir_hub/receive/receive.c](https://github.com/NN708/ESP-Homekit-IRHub/blob/31ea033016fe12f55b876cce2412db062e39d635/ir_hub/receive/receive.c)**
To use it, simply connect an IR receiver to GPIO 5, then generate the signal using your remote control. You can get the time of high or low level via the serial port. A little analysis is needed to decode it.

**Comment by kiralikbeyin** [comment]
@NN708 thanks for sharing.

I worked ir with arduino before.You can copy raw data and send it without decoding.
This raw data can be stored in eeprom or in fs

Please check https://github.com/z3t0/Arduino-IRremote/blob/master/examples/IRsendRawDemo/IRsendRawDemo.ino

I dont have any time now but i will try your lib soon.
